### ISSUE TITLE
Download link on packagist is out of date (v1.0.0)

### ISSUE THREAD

**Issue by terryupton** [clnt/alfred-tailwindcss-docs#2]
Great Plugin Matt. I use it all the time...I just tried to update and I noticed the link on packagist is version 1.0.0 and so isn't the latest.

http://www.packal.org/workflow/tailwind-docs-workflow-alfred

Jut in case you wanted to update.

Thanks again  👍🏻

**Comment by clnt** [comment]
Thanks, glad you like it. Cheers for pointing this out I didn't notice, I guess it was the rush to release a new version with the release of Tailwind v1 :)

Will look at getting it updated today 👍

**Comment by clnt** [comment]
Updated 👍
