### ISSUE TITLE
Tailwind CSS Version 2 Support

### ISSUE THREAD

**Issue by clnt** [clnt/alfred-tailwindcss-docs#4]
Tailwind 1.x docs now located at v1.tailwindcss.com - this will become a `tw1` command and require a workflow update.
Tailwind 2.x docs located in existing place so `tw` command will show results for v2.

**Comment by masonjo** [comment]
Great!  I just installed this and wondered why I got the older docs.

**Comment by clnt** [comment]
@masonjo Yeah apologies for any inconvenience mate, bit limited on time at the moment so as a 'quick solution' I updated the main index powering the `tw` command to point to the v1 docs as I assumed the majority of users will still be using this version. Then anyone who wants v2 docs would come here and look for an updated version in theory ;) 

Will have an update done for the workflow this weekend, hopefully this evening. I just want to make sure in this release that the workflow auto-update functionality is working, so any major changes like this in the future can easily be rolled out to existing users.

I plan to create the v2 index totally separate from the current meaning that anyone using the current workflow will still receive v1 results which should encourage coming here to update.

Look out for a 2.0.0 release :) Will ping you and close this issue once it is ready 👍

**Comment by clnt** [comment]
@masonjo Version 2.0.0 now released, enjoy :)

Didn't manage to sort the auto update functionality out, docs all relate to Python and this uses PHP. Will try and look into it more for a future version but needed to get this out as I myself want to take a deep dive in v2 :)
