### ISSUE TITLE
PHP Update fix for MacOS Monterey?

### ISSUE THREAD

**Issue by notsuhas** [clnt/alfred-tailwindcss-docs#9]
Hi, It looks like this workflow uses PHP and macOS 12 removed PHP. I installed PHP using homebrew, now the workflow must be updated to support the PHP script, and AFAIK Alfred takes care of the PHP path. Please do update this extension to support macOS 12.
Thanks

**Comment by jayhlee** [comment]
Thanks for creating this workflow!  Would be great if this workflow could be updated to support Monterey!

**Comment by clnt** [comment]
Hi,

Thanks for reporting this, currently I am still on Big Sur so haven't experienced any issues. From looking at other workflows experiencing the same issues it looks like its down to the PHP path needing to differ (and it being removed in Monterey).

I shall also need to upgrade the Algolia client dependency to support PHP 8 as I am getting errors when trying to debug using a script to force path.

I'll look at getting it updated hopefully tomorrow and also upgrade to Monterey to test. I am on an Intel mac - are you both using M1 macs? @notsuhas @jayhlee 

Cheers!

**Comment by notsuhas** [comment]
Yes, I'm using M1 MBP, Thanks for acknowledging the issue.

**Comment by jayhlee** [comment]
Yup, using M1. Thanks, @clnt!

**Comment by clnt** [comment]
Thanks for confirming, I have updated my MBP to Monterey this evening and have been working on getting it updated.

PHP has been all updated and did a bit of a refactor while at it so far. Just need to build the workflow file to handle the differing PHP paths which I will get sorted tomorrow and get a version `2.0.1` release out with some updated instructions specific to Monterey for anyone without PHP installed.

**Comment by clnt** [comment]
Hey @notsuhas @jayhlee 

New release has now been tagged v2.0.1 everything is working good on my end, are you able to test on M1 to ensure all okay? https://github.com/clnt/alfred-tailwindcss-docs/releases/tag/v2.0.1 

Cheers!

**Comment by notsuhas** [comment]
Yes, Its works beautifully on my M1. Thanks, mate. Cheers!

**Comment by jayhlee** [comment]
Sorry for the late reply. It doesn't seem to be working for me. When I type "tw", the workflow is activated, but typing a query after "tw" just breaks out of the workflow and defaults to my fallback results (Google query in my case).
![1](https://user-images.githubusercontent.com/25807445/142920270-6ab7dc76-ccdb-4f62-8bc6-8aa557233e8c.png)
![2](https://user-images.githubusercontent.com/25807445/142920288-9b679ebf-61a1-463e-8ead-77bdb4b47cdb.png)

**Comment by clnt** [comment]
Hey @jayhlee 

From an initial guess without seeing the workflow running with debug mode on it looks like it's unable to find your PHP path.

What is the output of the following commands in your terminal?

`which php` and `php -v`

If it cannot find php then it won't be setup in your $PATH correctly or not installed, or your installation is in a path which the script is not checking for.

**Comment by jayhlee** [comment]
Ah, that was the issue. Didn't realize that Monterey removed PHP. Thanks!
